### ISSUE TITLE
How i can make own started like your?

### ISSUE THREAD

**Issue by dalisoft** [mrbar42/trixion-starter#1]
Hi. Thanks for amazing thing. I am too made some html+js+css compile config for webpack, but everytime i copy packaejson and nodemodules file to new app. It too requires reinstall of all thing. How ican make starter like your? Thanks

**Comment by mrbar42** [comment]
if i understand your question correctly you are trying to create a template for your projects.
you can simply create a template folder that contains the base setup for your project and whenever you want to start a new project you can copy the folder all together to a new location and only then modify the files to fit the new project.

there are also automated solutions yet more advanced such as [yeoman](https://github.com/yeoman/yeoman)

**Comment by dalisoft** [comment]
Thanks a lot for answer
